### ISSUE TITLE
又g了

### ISSUE THREAD

**Issue by cjxyc** [eritpchy/webdav-aliyundriver-android#83]
好像又被封了

**Comment by eritpchy** [comment]
啥玩意

**Comment by cjxyc** [comment]
又看不了

**Comment by eritpchy** [comment]
发日志

**Comment by cjxyc** [comment]
![Uploading 20230215_182820.jpg…]()

**Comment by fjd1999999** [comment]
> 好像又被封了

没有啊，可以用现在

**Comment by d-maxheman** [comment]
我说怎么折腾半天还是看不了

**Comment by eritpchy** [comment]
截图看不见

**Comment by cjxyc** [comment]
"18.53:03 AlYunDriverClient 请求失败, url=/file/get_download_url, co de=400, body=("code":"DeviceSe*本本本本本本林本水水太水水kelnvalid" message"device session signature
erroryrequestld":"f02759fb-924d-418c-98aa-0f43c8ec903f, 0a0070a916764583876971844ea4b7")
- 18:53:03 n*.s*.w*.m*.DoGet /电影/2001太空漫游4K REMUX /2001.A.Space.Odyssey.1 968.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT.mkv doBody causes Exception!
net.sf.webdav.exceptions.WebdavException: 请求失败: /fle/get_download_url
at com.github.zxbu.webdavteambition.client.AlYunDriverClient.post(AiYunDriverClient.java:177)

**Comment by eritpchy** [comment]
往前点 应该有create_session 或 renew_session 那个也需要 很重要, 并且登录网页版看看登录设备管理里面有几个设备, 以及这个账户有没有多开, 类似功能软件也算的

**Comment by zsanto0324** [comment]
我刚刚也是不行 kodi里编辑视频源 把路径重新浏览一下就好了 谢谢作者大大 爱你

**Comment by roby411** [comment]
没问题啊 好用

**Comment by cjxyc** [comment]
没有看到有create_session和renew_session。设备管理里面有四个设备

**Comment by eritpchy** [comment]
应该有的, 你重启软件 截图第一页

**Comment by cjxyc** [comment]
我重新设置了一下网络位置，现在又能看了

**Comment by zsanto0324** [comment]
19:34:22 WebAppDeployer is deprecated. Use WebAppProvider
19:34:22 jetty-8.0.y.z-SNAPSHOT
19:34:22 Copying WEB-INF/libjar.file:/data/data/net.xdow.webdavaliyundriver/files/ietty/webapps/ROOT.war!/WEB-INF/lib/to/data/data/net.xdow.webdavaliyundriver/cache/
jetty-0.0.0.0-8989-ROOT.war--any-/webinf/WEB-INF/lib
19:34:22 java.util.MissingResourceException: Can't find bundle for base name org/eclipse/ietty/http/mime, locale zh_CN
19:34:22
19:34:22 java.util.MissingResourceException: Can't find bundle for base name org/eclipse/jetty/http/encoding, locale zh_CN
NO JSP Support for, did not find org.apache.jasper.servlet.JspServlet
19:34:25 AliYunDriverClienti4**1, url=https://api.aliyundrive.com/users/v1/users/device/renew_session,code=400,body=("code"."DeviceSe****************elnvalid""message"."device
session signature error" "requestld":"3635ee88-49f8-463-ba8c-34b49676176f,0a0070ae16764608695861997ea6d7")
19:34:25 unavailable
net.sf.webdav.exceptions. WebdavException：请求失败：https://api.aliyundrive.com/users/v1/users/ device/renew_session
at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYunDriverClient.java:177)
at com.github.zxbu.webdavteambition.manager.AliYunSessionManager.updateSession(AliYunSessionManager.java:74)
atcom.github.zxbu.webdavteambition.manager.AliYunSessionManager.start(AliYunSessionManager.java:88)
atcom.github.zxbu.webdavteambition.store.StartupService.startAliYunSessionManager(StartupService.java:62)
atcom.github.zxbu.webdavteambition.store.StartupService.init(StartupService.java:22)
atjavax.servlet.GenericServlet.init(UnknownSource:2)
atorg.eclipse.jetty.servlet.ServletHolder.c(UnknownSource:42)
at org.eclipse.jetty.servlet.ServletHolder.doStart(SourceFile:2)
atorg.eclipse.jetty.util.component.AbstractLifeCycle.start(UnknownSource:17)
at org.eclipse.jetty.servlet.ServletHandler.initialize (Unknown Source:123)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(UnknownSource:166)
at org.eclipse.jetty.webapp.WebAppContext.startContext(UnknownSource:8)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(Unknown Source:76)
at org.eclipse.jetty.webapp.WebAppContext.doStart(Unknown Source:12)
atorg.eclipse.jetty.util.component.AbstractLifeCycle.start(UnknownSource:17)
at org.mortbay.ijetty.deployer.a.scan(Unknown Source:471)
at org.mortbay.ijetty.deployer.a.doStart(Unknown Source:7)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(Unknown Source:17)
at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(Unknown Source:22)
atorg.eclipse.jetty.server.handler.AbstractHandler.doStart(UnknownSource:13)
at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(Unknown Source;7)
at org.eclipse.jetty.server.Server.doStart(Unknown Source:57)
atorq.eclipse.jetty.util.component.AbstractLifeCycle.start(UnknownSource:17)
at org.mortbay.ijetty.IJettyService.c(SourceFile:15)
at org.mortbay.ijetty.IJettyServiceSb.run(Unknown Source:4)
拍照转文字可能代码不准确

**Comment by zsanto0324** [comment]
atorg.eclipse.jetty.server.handler.HandlerCollection.handle(Unknown Source:22)
atorg.eclipse.jetty.server.handler.HandlerWrapper.handle(Unknown Source:12)
at org.eclipse.jetty.server.Server.handle(Unknown Source:97)
at org.eclipse.jetty.server.HttpConnection.a(Unknown Source:164)
at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(SourceFile:18)
at org.eclipse.jetty.http.HttpParser.parseNext(Unknown Source:937)
at org.eclipse.jetty.http.HttpParser.parseAvailable(Unknown Source:0)
at org.eclipse.jetty.server.BlockingHttpConnection.handle(SourceFile:2)
at org.eclipse.jetty.server.nio.BlockingChannelConnector$BlockingChannelEndPoint.run(SourceFile:4)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(SourceFile:3)
atjava.lang.Thread.run(Thread.java:919)
19:36:13
*nDriverFile SystemStore getstoredobject: /剧/中国奇谭/Yao-Chinese. Folktales.2023.S01E01.2160p.WEB-DL.H264.AAC-OurTV.mp4
19:36:13
*nDriverFile SystemStore getStoredobject: /剧/中国奇谭/Yao-Chinese.Folktales.2023.S01E01.2160p.WEB-DL.H264.AAC-OurTV.mp4
19:36:13
*nDriverFile SystemStore getStoredobject: /剧/中国奇谭/Yao-Chinese.Folktales.2023.S0E01.2160p.WEB-DL.H264.AAC-OurTV.mp4
19:36:13
*nDriverFile SystemStore getResourceContent: /剧/中国奇谭/Yao-Chinese.Folktales.2023.S01E01.2160p.WEB-DL.H264.AAC-OurTV.mp4
19:36:13
*nDriverFileSystemStore getResourceLength:/剧/中国奇谭/Yao-Chinese.Folktales.2023.S01E01.2160p. WEB-DL.H264.AAC-OurTV.mp4
19:36:14 AliYunDriverClient 请求失败，url=/file/ get_download_url, code=400,body =f'code':"DeviceSetttttxxxxxxxxxxtelnvalid',message':'device session signature
error" "requestld":"e2242d78-2f12-4ce8-a2d6-f63d1b507ad4,0a0070ab16764609782273719ee76f")
19:36:14 n*.s*.w*.m*.DoGet /剧/中国奇谭/Yao-Chinese.Folktales.2023.S01E01.2160p.WEB-DL.H264.AAC-OurTV.mp4 do Body causes Exception!
net.sf. webdav.exceptions.WebdavException：请求失败：/file/get_download_url
at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYunDriverClient.java:177)
at com.github.zxbu.webdavteambition.store.AliYunDriverClientService.download(AliYunDriverClientService.java:336)
at com.github.zxbu.webdavteambition.store.AliYunDriverFileSystemStore.getResourceContent(AliYunDriverFileSystemStore.java:93)
atnet.sf.webdav.methods.DoGet.doBody(DOGet.java:68)
atnet.sf.webdav.methods.DoHead.execute(DoHead.java:155)
at net.sf.webdav.WebDavServletBean.e(WebDavServletBean.java:134)
atjavax.servlet.http.HttpServlet.service(UnknownSource:4)
at org.eclipse.jetty.servlet.ServletHolder.handle(Unknown Source:64)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(SourceFile:4)
atcom.github.zxbu.webdavteambition.filter.ErrorFilter.doFilter(ErrorFilter.java:50)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(SourceFile:2)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(Unknown Source:105)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(Unknown Source:8)
at org.eclipse.jetty.security.SecurityHandler.handle(SourceFile:2)
atorg.eclipse.jetty.server.session.SessionHandler.doHandle(UnknownSource:26)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(Unknown Source:108)

**Comment by eritpchy** [comment]
你和另外一个issue也是同样的问题 有没有机会找条数据线插电脑给我远程一下你的手机, 加q 276308768

**Comment by tom668998** [comment]
电视机kodi+手机上阿里云盘和wedbav,电视上的kodi播放电影显示一个或多个项目播放失败

**Comment by roby411** [comment]
> 电视机kodi+手机上阿里云盘和wedbav,电视上的kodi播放电影显示一个或多个项目播放失败

额 我也出问题 一样的

**Comment by maxthontl** [comment]
> > 电视机kodi+手机上阿里云盘和wedbav,电视上的kodi播放电影显示一个或多个项目播放失败
> 
> 额 我也出问题 一样的

俺也一样

**Comment by naihe138** [comment]
重启webdav，可以解决。每次只能看一个视频，日志可能太多了，看完一个就卡了

**Comment by tom668998** [comment]
> > > 电视机kodi+手机上阿里云盘和wedbav,电视上的kodi播放电影显示一个或多个项目播放失败
> > 
> > 
> > 额 我也出问题 一样的
> 
> 俺也一样

解决了，兄弟是不是往云盘里存毛片了？账号被官方封了，换个账号就好了

**Comment by roby411** [comment]
> > > > 电视机kodi+手机上阿里云盘和wedbav,电视上的kodi播放电影显示一个或多个项目播放失败
> > > 
> > > 
> > > 额 我也出问题 一样的
> > 
> > 
> > 俺也一样
> 
> 解决了，兄弟是不是往云盘里存毛片了？账号被官方封了，换个账号就好了

好几个人都被封号？？扯 手机端都用的好好的

**Comment by shinemoo** [comment]
> > > > 电视机kodi+手机上阿里云盘和wedbav,电视上的kodi播放电影显示一个或多个项目播放失败
> > > 
> > > 
> > > 额 我也出问题 一样的
> > 
> > 
> > 俺也一样
> 
> 解决了，兄弟是不是往云盘里存毛片了？账号被官方封了，换个账号就好了

应该不可能，这么多人都同一个bug。我电脑上能正常登阿里云，电视上用小白云盘也能调kodi看

**Comment by zsanto0324** [comment]
作者大大已经修改好了 大家耐心等待下新的补丁版本。

**Comment by eritpchy** [comment]
试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

**Comment by tom668998** [comment]
> 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

刚开始还行，不一会儿又挂了。

**Comment by Greatwallcorner** [comment]
无效的设备id是什么原因呢

08:36.53 AIIYunDriverclient 请求失败，
url＝https:/apialiyundrive.com/token/refresh， code＝400，body＝t＂＇code＂.＂Invalidparameter.Clientid＂， ＂ message＂.＂ Theinput parameter client_id is not valid.＂， requestld＂:null


识图的

**Comment by wesurevip** [comment]
> 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1

这个版本过段时间又跳无效链接，无法播放

**Comment by eritpchy** [comment]
> > 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1
> 
> 这个版本过段时间又跳无效链接，无法播放

过多久

**Comment by wesurevip** [comment]
> > > 试试2.0.1 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.1
> 
> > 
> 
> > 这个版本过段时间又跳无效链接，无法播放
> 
> 
> 
> 过多久

没特别注意，可能半个小时左右

**Comment by eritpchy** [comment]
2.0.2 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.2

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4
